spring:
  profiles.active: standalone
   
    
---
spring:
  profiles: default  
  jpa:
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

      
---
spring:
  profiles: standalone
  thymeleaf.cache: false
  jpa:    
    show-sql: false
    hibernate.ddl-auto: create    

liquibase:
  change-log: ch/hes/db/changelog/db.changelog-master.yml
            
security:
  user:
    password: weak
    
